INSERT INTO villain (id, arch_rival, name, hero_name, height, weight, special_power, intelligence, strength, power, speed, agility, description, story, image_url) VALUES
(1, 'Spiderman', 'Maxwell Dillon', 'Electro', 180, 74, 'Electric manipulation', 93, 56, 77, 66, 88, 'Electro is a long-standing rival of Spider-Man who is able to absorb and project massive amounts of electricity', 'While Maxwell "Max" Dillon, an electrical engineer and lineman, was repairing a power line, a freak lightning accident caused a mutagenic change that transformed him into a living electrical capacitor.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/620-spider-man.jpg'),
(2, 'Spiderman', 'Otto Octavius', 'Doctor Octopus', 175, 110, 'Superhuman Strength, tentacle-like arms', 94, 48, 53, 33, 65, 'Genius supervillain who can control four mechanical arms grafted onto his body', 'Otto Octavius was a brilliant but arrogant nuclear physicist who was caught in an explosion at work that left him brain damaged and fused his mechanical tentacles of his own creation to his body, turning him into a crazed super villain.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/225-doctor-octopus.jpg'),
(3, 'Batman', 'Selina Kyle', 'Cat Woman', 175, 61, 'Master burglar, gymnast and acrobat', 69, 11, 27, 33, 85, 'Infamous cat-burglar', 'As deadly as she is beautiful, infamous cat-burglar Selina Kyle uses her nine lives to walk the razors edge between light and darkness in Gotham City.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/165-catwoman.jpg');

--INSERT INTO hero (id, name, hero_name, height, weight, special_power, intelligence, strength, power, speed, agility, description, story, image_url) VALUES
--(1, 'Peter Parker', 'Spiderman', 178, 74, 'Precognitive spider-sense ability', 90, 55, 74, 67, 85, 'Peter Parkers arachnid abilities give him powers he uses to help others, while his personal life offers plenty of obstacles', 'American teenager Peter Parker, a poor sickly orphan, is bitten by a radioactive spider. As a result of the bite, he gains superhuman strength, speed, and agility along with the ability to cling to walls', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/620-spider-man.jpg'),
--(2, 'Tony Stark', 'Iron Man', 198, 191, 'Flight, weapons, special suit(armor)', 100, 85, 100, 58, 64, 'Billionaire. Philanthropist. Inventor', 'Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/346-iron-man.jpg'),
--(3, 'Bruce Wayne', 'Batman', 178, 77,'Genius intellect', 81, 40, 63, 29, 50, 'The Dark Knight' ,'After witnessing the murder of his parents Dr. Thomas Wayne and Martha Wayne as a child, he swore vengeance against criminals, an oath tempered by a sense of justice.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/69-batman.jpg'),
--(4, 'Diana Prince', 'Wonder Woman', 183, 74, 'Fligth, Speed, Stamina, Superhuman sight', 88, 100, 100, 79, 100, 'Princess of the Amazons, Goddess of Truth', 'Wonder Woman was sculpted from clay by her mother Queen Hippolyta and was given a life to live as an Amazon, along with superhuman powers as gifts by the Greek gods.', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/720-wonder-woman.jpg');
